src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Alpha2Code__c</fullName>
        <label>Alpha2Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alpha3Code__c</fullName>
        <label>Alpha3Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capital__c</fullName>
        <label>Capital</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegionalBlocs__c</fullName>
        <label>RegionalBlocs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CountryDataSchedulerTest.cls
/**
 * @author Zhanat.Kanatbekov on 23.07.2024.
 * @description Test class for CountryDataScheduler class
 */

@IsTest
private class CountryDataSchedulerTest {

    @isTest
    static void testCountryDataScheduler() {
        // Mock HTTP response
        Test.setMock(HttpCalloutMock.class, new CountryLayerServiceTest.CountryLayerHttpMock());

        // Schedule the job
        String jobId = System.schedule('CountryDataSchedulerJob', '0 0 0 * * ?', new CountryDataScheduler());

        // Retrieve the scheduled job
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals('0 0 0 * * ?', ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);

        // Simulate the job execution
        Test.startTest();
        CountryLayerService.fetchCountryData();
        Test.stopTest();

        // Verify that the country data has been fetched and processed
        List<Country__c> countries = [SELECT Name, Alpha2Code__c, Alpha3Code__c, Capital__c, Region__c, RegionalBlocs__c FROM Country__c];
        System.assertEquals(1, countries.size());
        System.assertEquals('Test Country', countries[0].Name);
    }
}